// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountController from "./account_controller.js"
application.register("account", AccountController)

import CandidacyController from "./candidacy_controller.js"
application.register("candidacy", CandidacyController)

import CarouselController from "./carousel_controller.js"
application.register("carousel", CarouselController)

import ContactController from "./contact_controller.js"
application.register("contact", ContactController)

import ExperienceController from "./experience_controller.js"
application.register("experience", ExperienceController)

import FaqController from "./faq_controller.js"
application.register("faq", FaqController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import LockController from "./lock_controller.js"
application.register("lock", LockController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NewProfileController from "./new_profile_controller.js"
application.register("new-profile", NewProfileController)

import ProfileFormController from "./profile_form_controller.js"
application.register("profile-form", ProfileFormController)

import ProgressController from "./progress_controller.js"
application.register("progress", ProgressController)

import SearchFormController from "./search_form_controller.js"
application.register("search-form", SearchFormController)

import SliderController from "./slider_controller.js"
application.register("slider", SliderController)

import TomSelectController from "./tom_select_controller.js"
application.register("tom-select", TomSelectController)

import TypedJsController from "./typed_js_controller.js"
application.register("typed-js", TypedJsController)
