// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountController from "./account_controller"
application.register("account", AccountController)

import ButtonMenuController from "./button_menu_controller"
application.register("button-menu", ButtonMenuController)

import CalendlyController from "./calendly_controller"
application.register("calendly", CalendlyController)

import CandidacyController from "./candidacy_controller"
application.register("candidacy", CandidacyController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ContactController from "./contact_controller"
application.register("contact", ContactController)

import DisplayController from "./display_controller"
application.register("display", DisplayController)

import DotPathController from "./dot_path_controller"
application.register("dot-path", DotPathController)

import DualSliderController from "./dual_slider_controller"
application.register("dual-slider", DualSliderController)

import DynamicFormController from "./dynamic_form_controller"
application.register("dynamic-form", DynamicFormController)

import ExperienceController from "./experience_controller"
application.register("experience", ExperienceController)

import FaqController from "./faq_controller"
application.register("faq", FaqController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormRedirectController from "./form_redirect_controller"
application.register("form-redirect", FormRedirectController)

import FormSubmitterController from "./form_submitter_controller"
application.register("form-submitter", FormSubmitterController)

import GtmController from "./gtm_controller"
application.register("gtm", GtmController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HiddenFormController from "./hidden_form_controller"
application.register("hidden-form", HiddenFormController)

import LegendController from "./legend_controller"
application.register("legend", LegendController)

import LockController from "./lock_controller"
application.register("lock", LockController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import NewProfileController from "./new_profile_controller"
application.register("new-profile", NewProfileController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import PopupController from "./popup_controller"
application.register("popup", PopupController)

import ProfileFormController from "./profile_form_controller"
application.register("profile-form", ProfileFormController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)

import RadioController from "./radio_controller"
application.register("radio", RadioController)

import ScrollCarouselController from "./scroll_carousel_controller"
application.register("scroll-carousel", ScrollCarouselController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import TenantMenuController from "./tenant_menu_controller"
application.register("tenant-menu", TenantMenuController)

import TimesheetController from "./timesheet_controller"
application.register("timesheet", TimesheetController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
