meta_product_name: "Demain"
meta_title: "Demain - Plus besoin de changer de boîte pour changer le monde"
meta_description: "Aujourd'hui principalement au service des entreprises, le Capital Humain est un bien commun à remettre au service des causes sociales et environnementales. Demain permet ainsi aux salariés en entreprise de travailler à temps partiel pour une cause d'intérêt général : que vous soyez une association, une entreprise ou un salarié : nous avons une solution pour vous!"
meta_image: "bannerog.jpg"
