meta_product_name: "Demain Works"
meta_title: "Demain Works - Talents engagés et solidaires"
meta_description: "Plus besoin de choisir entre un job qui paye et un job qui compte ! Demain permet aux personnes salariées souhaitant s'engager de travailler pour une cause d'intérêt général en facilitant le partage du temps de travail et des compétences entre entreprises et associations"
meta_image: "bannerog.jpg"
